parameters:
    open_orchestra_elastica_admin.populator.manager.class: OpenOrchestra\ElasticaAdmin\Populator\ElasticaPopulatorManager
    open_orchestra_elastica_admin.populator.content.class: OpenOrchestra\ElasticaAdmin\Populator\Strategies\ContentPopulator
    open_orchestra_elastica_admin.populator.node.class: OpenOrchestra\ElasticaAdmin\Populator\Strategies\NodePopulator

services:
    open_orchestra_elastica_admin.populator.manager:
        class: '%open_orchestra_elastica_admin.populator.manager.class%'

    open_orchestra_elastica_admin.populator.content:
        class: '%open_orchestra_elastica_admin.populator.content.class%'
        arguments:
            - '@open_orchestra_elastica_admin.indexor.content'
            - '@open_orchestra_model.repository.content'
            - '%open_orchestra_backoffice.orchestra_choice.front_language%'
        tags:
            - { name: open_orchestra_elastica_admin.populator.strategy}

    open_orchestra_elastica_admin.populator.node:
        class: '%open_orchestra_elastica_admin.populator.node.class%'
        arguments:
            - '@open_orchestra_elastica_admin.indexor.node'
            - '@open_orchestra_model.repository.node'
        tags:
            - { name: open_orchestra_elastica_admin.populator.strategy}
