parameters:
    open_orchestra_elastica_admin.transformer.content.class: OpenOrchestra\ElasticaAdmin\Transformer\ContentTransformer
    open_orchestra_elastica_admin.transformer.node.class: OpenOrchestra\ElasticaAdmin\Transformer\NodeTransformer

services:
    open_orchestra_elastica_admin.transformer.content:
        class: '%open_orchestra_elastica_admin.transformer.content.class%'
    open_orchestra_elastica_admin.transformer.node:
        class: '%open_orchestra_elastica_admin.transformer.node.class%'
        arguments:
            - '@open_orchestra_backoffice.display_block_manager'
